# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 签到

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout
      run: |
        git clone https://github.com/kuilei0926/xixunyun.git ~/xixunyun
        pip install requests
        pip install rsa
    - name: '运行 【签到】'
      run: |
        cd ~/xixunyun
        python rsa.py
    env:
          USER: ${{ secrets.USER }}
          SIGN_GPS:  ${{ secrets.SIGN_GPS }}
          MODEL:  ${{ secrets.MODEL }}
          SET:  ${{ secrets.SET }}
          REMARK_NAME:  ${{ secrets.REMARK_NAME }}

