# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 签到

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout
      run: |
        git clone https://github.com/kuilei0926/xixunyun.git ~/xixunyun
    - name: '运行 【签到】'
      run: |
        cd ~/xixunyun
        python xixunyun.py
    env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          SIGN_GPS:  ${{ secrets.SIGN_GPS }}
          LATITUDE:  ${{ secrets.LATITUDE }}
          LONGITUDE:  ${{ secrets.LONGITUDE }}:  
